Users/peram/niresults/add results client
ni/nisystemlink-clients-python pull request #82
Opened 2024-11-07 08:29 UTC by Madhan-Reddy-ni

- [ ] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nisystemlink-clients-python/blob/master/CONTRIBUTING.md).

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/nisystemlink-clients-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR adds client methods for all of the `nitestmonitor` result endpoints as well as testing for these endpoints.

### Why should this Pull Request be merged?

This is an enhancement to the existing test monitor client and will enable users to more easily interact with SystemLink test results.

### What testing has been done?

Auto testing is included against NI's test tier.

API Swagger Link - [Results](https://dev-api.lifecyclesolutions.ni.com/niapis/?urls.primaryName=Test+Monitor#/results)

2024-11-12 06:48 UTC, Madhan-Reddy-ni commented on examples/result/results.py
> +create_response = create_some_results()
Updated to call the create_results first and then the get_results..

2024-11-18 03:15 UTC, santhoshramaraj approved these changes

2024-11-22 22:34 UTC, adamarnesen approved these changes

2025-02-06 22:54 UTC, rbell517 requested changes

2025-02-06 22:54 UTC, rbell517 commented on nisystemlink/clients/result/models/_query_results_request.py
> +    - `status`: String for the status of the result
Status is actually a two-field object with a string statusName field and an enum statusType field. The name field is fully settable but should be ignored unless statusType is set to Custom. Generally queries should be checking the statusType field. 

![image](https://github.com/user-attachments/assets/2f1ade0b-4c77-4697-a884-be4bded55405)

You can point them to the `StatusType` model class

2025-02-06 22:54 UTC, rbell517 commented on nisystemlink/clients/result/models/_query_results_request.py
> +    continuation_token: Optional[str] = None
We prefer to base off of `WithPaging` to get the continuation token field. That will help when we have a more reusable paging implementation.

2025-02-06 22:54 UTC, rbell517 commented on nisystemlink/clients/result/models/_result.py
> +    status_type_summary: Optional[Dict[str, int]]
A dictionary of string to int is what the swagger types this as, but in practice the key will be the status type enum

2025-02-06 22:54 UTC, rbell517 commented on nisystemlink/clients/result/models/_result.py
> +    is_finalized: Optional[bool]
Finalized never made it to the public API documentation. Its a half-baked feature right now, so I would leave it off the client object to avoid any confusion.

2025-02-06 22:54 UTC, rbell517 commented on nisystemlink/clients/result/_result_client.py
> +            invalid arguments.
```suggestion
                invalid arguments.
```

2025-02-06 22:54 UTC, rbell517 commented on examples/result/results.py
> +            status=StatusObject(status_type=StatusType.PASSED, status_name="Passed"),
Can we make this easier? Can this be settable with just the StatusType enum OR the full status object? If we do this we should make it clear in the example, with using just the StatusType enum and one setting a custom status that uses the full object

2025-02-06 22:54 UTC, rbell517 commented on examples/result/results.py
> +    filter=f'programName="{program_name}" && hostName="{host_name}"',
A filter that filters by status would be a good example, since its a bit different and I expect it to be among the more common filter clauses

2025-02-06 22:54 UTC, rbell517 commented on nisystemlink/clients/result/_result_client.py
> +    ) -> models.CreateResultsPartialSuccess:
Update shouldn't return the create response for updates. I think this is really just point to the name being off. The service uses the same object for both. The swagger has them as different response objects, but I think thats OK to ignore. It properly uses the same type in the results collection in both.

2025-02-06 22:54 UTC, rbell517 commented on nisystemlink/clients/result/_result_client.py
> +        self, results: List[Result], replace: bool = False
Technically the allowed values for a result update is not identical to the returned result. You can't directly update updatedAt or the status summary for example. Those are enough of an edge case that I wouldn't want to make this client harder to use to account for those. For example, I wouldn't want to require a separate mapping call to map from the Result returned from a query to the the Result to provide to the update. I like that you can just set the new value you want and send the update.

The other problem with this is the workspace field. The service will change the workspace permission you're required to have based on whether the workspace field is included in the update. If you include workspace, you now need delete and create privileges in that workspace to perform the update, even if the workspace isn't being changed. This is because we don't know whether the workspace is being updated ahead of time. 

This has tripped up a good number of people, particularly if they are operating under the automated agent role that does not have delete privileges. Maybe the right answer is to actually change the service behavior to only require delete/create when the workspace is being changed. That wouldn't be a trivial change.

We have a couple options. For the first issue we can implicitly/silently drop fields from Result that aren't allowed to be updated. That could be confusing; would documentation be good enough? We could raise an error, but now you're back to need another step between query and update. For the second issue, if we're not going to change the service behavior the only improvement I have is to add another boolean allow_workspace_update field to the function params that would keep workspace fields if true, otherwise would replace them with None.

@adamarnesen I'm interested in an outside perspective on this.

2025-02-06 22:54 UTC, rbell517 commented on nisystemlink/clients/result/models/_query_results_request.py
> +class ResultField(str, Enum):
If I had my way I'd say projections should be required to be provided by callers, but its probably a bridge to far.

2025-02-06 22:54 UTC, rbell517 commented on tests/integration/result/test_result_client.py
> +    def test__create_multiple_results_and_get_results_with_count_at_least_one_count(
Make sure you're using the given__when__then naming convention

2025-02-24 19:34 UTC, priyadarshini-ni commented on nisystemlink/clients/result/_result_client.py
> +    ) -> models.CreateResultsPartialSuccess:
The response object's name for create and update has been changed to `ResultsPartialSuccess` to use for both cases

2025-02-24 19:35 UTC, priyadarshini-ni commented on examples/result/results.py
> +    filter=f'programName="{program_name}" && hostName="{host_name}"',
The filter has been modified to filter by status. eg.status.statusType == \"Passed\"

2025-02-24 19:38 UTC, priyadarshini-ni commented on examples/result/results.py
> +            status=StatusObject(status_type=StatusType.PASSED, status_name="Passed"),
Based on the second suggestion, the examples have been provided to showcase how the `StatusObject` can be set using only the `StatusType` enum and also both `StatusType` and `StatusName` in case of custom value.

2025-02-24 19:40 UTC, priyadarshini-ni commented on nisystemlink/clients/result/models/_query_results_request.py
> +    - `status`: String for the status of the result
The status field has been pointed to the `StatusType` model class

2025-02-25 09:59 UTC, priyadarshini-ni commented on nisystemlink/clients/result/models/_query_results_request.py
> +class ResultField(str, Enum):
The Result Query OrderBy Field enum and Result Values Query Field enum have been made separate to show the distinction.

The ResultField.Product field has also been added to the mentioned enums.

Projection has also been included to the query-results API with the supported values as per swagger.

2025-02-25 12:40 UTC, priyadarshini-ni commented on nisystemlink/clients/result/_result_client.py
> +        self, results: List[Result], replace: bool = False
Based on the suggestion for updating workspace, `allow_workspace_update` field has been included to the function params.

For the first issue, would you recommend creating separate request models for UpdateResults and QueryResults to distinguish the fields that can be updated from the query results?

2025-02-25 18:45 UTC, priyadarshini-ni commented on nisystemlink/clients/result/models/_result.py
> +    is_finalized: Optional[bool]
This has been removed from the client model

2025-02-25 20:52 UTC, priyadarshini-ni commented on nisystemlink/clients/result/_result_client.py
> +        self, results: List[Result], replace: bool = False
For the initial problem mentioned, another model for UpdateRequest has been created to differentiate between the fields that can be updated in a query response. Dropping the fields from Result or adding more documentation could end up being more confusing as you mentioned.

For updating workspace field, `allow_workspace_update` field has been included to the function params which would perform as suggested.

2025-02-25 21:35 UTC, adamarnesen commented on nisystemlink/clients/result/_result_client.py
> +        self, results: List[Result], replace: bool = False
I think having a separate model is the better approach here. Trying to remove fields from the response model would be confusing. 

Maybe in the future we add a helper that allows you to easily create an update model from a response model and that's how you "downcast" to get rid of the fields. 

Is there an option to have the `update model` be a parent class of the `response model`?

2025-02-25 21:55 UTC, rbell517 commented on nisystemlink/clients/result/_result_client.py
> +        self, results: List[Result], replace: bool = False
It should be doable to make an update request from an existing `Result` but we wouldn't want to make the update model the base class of `Result`, I think that would be confusing.

2025-02-25 22:27 UTC, rbell517 requested changes

2025-02-25 22:27 UTC, rbell517 commented on nisystemlink/clients/result/_result_client.py
> +        if not allow_workspace_update:
Make sure to include test coverage of this change if we keep it around

2025-02-25 22:27 UTC, rbell517 commented on nisystemlink/clients/result/_result_client.py
> +    def query_results_paged(
I'd rather this just be query_results. That is inconsistent with products but we'll get products changed to match this

2025-02-25 22:27 UTC, rbell517 commented on nisystemlink/clients/result/_result_client.py
> +    def query_results_paged(
Same for get_results_paged -> get_results

2025-02-25 22:27 UTC, rbell517 commented on nisystemlink/clients/result/_result_client.py
> +        self, results: List[Result], replace: bool = False
With the separate update request class I think we can remove the allow_workspace_update parameter from the update_result function, since those update request objects need to be explicitly constructed. When we add back an easy way to create an update request from a `Result` we can revisit this. It will probably make more sense to include that allow_workspace_update field on the function that creates the update request from the Result instead of on the update_result function directly.

2025-02-26 13:01 UTC, priyadarshini-ni commented on nisystemlink/clients/result/models/_update_result_request.py
> +    status: StatusObject
Updated

2025-02-26 13:02 UTC, priyadarshini-ni commented on nisystemlink/clients/result/models/_result.py
> +    status: StatusObject
All fields have been marked optional

2025-02-26 13:03 UTC, priyadarshini-ni commented on docs/getting_started.rst
> +The :class:`.ResultClient` class is the primary entry point of the Result API.
Modified the docs

2025-02-26 13:04 UTC, priyadarshini-ni commented on nisystemlink/clients/result/_result_client.py
> +class ResultClient(BaseClient):
The client functions of ResultClient have been moved to TestMonitorClient along with the models

2025-02-26 13:09 UTC, priyadarshini-ni commented on nisystemlink/clients/result/_result_client.py
> +        self, results: List[Result], replace: bool = False
The update model and base model have been made into separate models. As update API would be using a separate request model, the `allow_workspace_update` parameter has been removed.

2025-02-26 17:50 UTC, SSSantosh18 approved these changes

2025-02-26 17:50 UTC, SSSantosh18 commented on nisystemlink/clients/testmonitor/models/_query_results_request.py
> +class Projection(str, Enum):
```suggestion
class ResultProjection(str, Enum):
```

2025-02-26 17:50 UTC, SSSantosh18 commented on nisystemlink/clients/testmonitor/models/_result.py
> +        extra = Extra.allow
is this to not face any validation error due to not having an attribute for IsFinalized?

Looks like it will allow any new parameters to be automatically added to the object without throwing validation error. Should we set this to [Ignore](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra) so that fields like IsFinalized is not included in the response object?

2025-02-26 17:50 UTC, SSSantosh18 commented on nisystemlink/clients/testmonitor/models/_results_partial_success.py
> +    failed: Optional[List[Result]] = None
failed should point to the request object because it should be same as the request body. There will be additional params in the result object

2025-02-26 17:50 UTC, SSSantosh18 commented on nisystemlink/clients/testmonitor/models/_results_partial_success.py
> +    failed: Optional[List[Result]] = None
there should be two differnet models for create and update

2025-02-26 17:50 UTC, SSSantosh18 commented on tests/integration/testmonitor/test_testmonitor.py
> +        )
we can map it with more simple code like

```
UpdateResultRequest(**result.dict())
```

2025-02-27 03:17 UTC, SSSantosh18 commented on examples/result/results.py
> +from nisystemlink.clients.core import HttpConfiguration
can we move this under testmonitor folder

2025-02-27 04:26 UTC, santhoshramaraj commented
@SSSantosh18 @priyadarshini-ni @rbell517 , when creating the `ProductsClient` it was agreed that it is better to avoid the `TestMonitorClient` concept as it may not be inituitive to users as they don't see the `TestMonitor` anywhere on the webpage and it is best to use separate clients for Products, Results and Steps.

2025-02-27 07:23 UTC, priyadarshini-ni commented on tests/integration/testmonitor/test_testmonitor.py
> +        )
Simplified the mapping

2025-02-27 07:24 UTC, priyadarshini-ni commented on nisystemlink/clients/testmonitor/models/_results_partial_success.py
> +    failed: Optional[List[Result]] = None
Created new models for Create and Update partial success reponse. The failed within that model has also been pointed to the request body

2025-02-27 08:16 UTC, priyadarshini-ni commented on nisystemlink/clients/testmonitor/models/_query_results_request.py
> +class Projection(str, Enum):
Updated

2025-02-27 08:19 UTC, priyadarshini-ni commented on examples/result/results.py
> +from nisystemlink.clients.core import HttpConfiguration
The example for `results.py` has been moved under `testmonitor` folder. The file name has been retained.

2025-02-28 04:05 UTC, santhoshramaraj submitted a review, later dismissed

2025-02-28 04:05 UTC, santhoshramaraj commented on nisystemlink/clients/testmonitor/models/_result.py
> +
Create a constant class for all standard `StatusType` as in most use cases users don't use the `status_name` and it is an additional step to create a `StatusObject`

```suggestion
class StandardResultStatus:
    LOOPING = StatusObject(StatusType.LOOPING)
    SKIPPED = StatusObject(StatusType.SKIPPED)
    ...
   
```

2025-02-28 05:45 UTC, priyadarshini-ni commented on nisystemlink/clients/testmonitor/_test_monitor_client.py
> +    def query_results(self, query: models.QueryResultsRequest) -> models.PagedResults:
Please refer to this comment where it was suggested to removed `paged` - https://github.com/ni/nisystemlink-clients-python/pull/82#discussion_r1970624403. 
Is there any reasoning for including it?

2025-02-28 06:45 UTC, priyadarshini-ni commented on nisystemlink/clients/testmonitor/models/_result.py
> +
Added as suggested

2025-02-28 06:45 UTC, priyadarshini-ni commented on nisystemlink/clients/testmonitor/models/_result.py
> +class StatusObject(JsonModel):
Updated

2025-02-28 06:45 UTC, priyadarshini-ni commented on examples/testmonitor/results.py
> +# Setup the server configuration to point to your instance of SystemLink Enterprise
Updated as suggested

2025-02-28 06:47 UTC, priyadarshini-ni commented
> @SSSantosh18 @priyadarshini-ni @rbell517, when creating the `ProductsClient`, it was agreed that it is better to avoid the `TestMonitorClient` concept, as it may not be intuitive to users, as they don't see the `TestMonitor` anywhere on the SLE webpage. It is better to use separate clients for Products, Results, and Steps for the user to relate to the different pages or hierarchy.
> 
> FYI - @adamarnesen
Related comment - https://github.com/ni/nisystemlink-clients-python/pull/82#discussion_r1970617384. Confirmation on this would be helpful to proceed further.

2025-02-28 07:04 UTC, SSSantosh18 commented on nisystemlink/clients/testmonitor/_test_monitor_client.py
> +    def query_results(self, query: models.QueryResultsRequest) -> models.PagedResults:
@santhoshramaraj, if not mentioned paged, do you feel a user might confuse this as a client method that returns all items at once?

2025-02-28 16:38 UTC, rbell517 commented on nisystemlink/clients/result/_result_client.py
> +class ResultClient(BaseClient):
> @SSSantosh18 @priyadarshini-ni @rbell517, when creating the ProductsClient, it was agreed that it is better to avoid the TestMonitorClient concept, as it may not be intuitive to users, as they don't see the TestMonitor anywhere on the SLE webpage. It is better to use separate clients for Products, Results, and Steps for the user to relate to the different pages or hierarchy.
> 
> FYI - @adamarnesen

We don't show Test Monitor in our SLE UI, but it is what the API is named in the Swagger page, which is our official API documentation. Since this a client for that API I think makes sense to name the client accordingly. I also want to reinforce that steps and results are concepts that work together and putting them on the same client does that.

2025-02-28 17:09 UTC, rbell517 approved these changes

2025-02-28 17:09 UTC, rbell517 commented on nisystemlink/clients/testmonitor/models/_result.py
> +class StatusObject(JsonModel):
This would mean we'll end up with a separate StepStatus when we add steps. The API uses the same type for both, but them being separate in the client isn't the end of the world. I would good with just calling this `Status` and moving it to its own file. With the other change to add the static helpers to this class you'd get a nice `Status.PASSED` experience, which is great.

2025-03-03 06:15 UTC, priyadarshini-ni commented on nisystemlink/clients/testmonitor/models/_result.py
> +
Moved to `Status` class

2025-03-05 08:22 UTC, priyadarshini-ni commented on nisystemlink/clients/testmonitor/_test_monitor_client.py
> +    def query_results(self, query: models.QueryResultsRequest) -> models.PagedResults:
The `*_paged` nomenclature has been removed from the results client. Similar changes for products API can be taken up in a different PR.

2025-03-05 08:25 UTC, merged