feat: Add Client for Asset Management (Asset) API
ni/nisystemlink-clients-python pull request #86
Opened 2024-12-04 14:16 UTC by sam-rishi

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/nisystemlink-clients-python/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR adds API Client Module for `Asset` microservice in the `Asset Management` service.

### Why should this Pull Request be merged?

The `AssetManagementClient` makes it easier for users to interact with the endpoints of `Asset Management` service by just creating an instance of it.

### What testing has been done?

Automated integration tests are included.

API Link: [Swagger Link](https://dev-api.lifecyclesolutions.ni.com/niapis/?urls.primaryName=Asset+Management#/)

2025-02-10 21:12 UTC, rbell517 requested changes

2025-02-10 21:12 UTC, rbell517 commented on nisystemlink/clients/assetmanagement/models/_query_assets.py
> +    calibratable_only: bool
The swagger has a block comment that explains what this boolean does that should be duplicated here

2025-02-10 21:12 UTC, rbell517 commented on nisystemlink/clients/assetmanagement/models/_query_assets.py
> +    descending: bool
I'm pretty sure descending is supposed to be optional but it looks like its currently required. I think it would be better to make it optional for if this gets fixed. FYI @CiprianAnton

2025-02-10 21:12 UTC, rbell517 commented on nisystemlink/clients/assetmanagement/models/_query_location.py
> +class SystemConnection(Enum):
You've duplicated SystemConnection and AssetPresence. These are the same for all the APIs.

2025-02-10 21:12 UTC, rbell517 commented on nisystemlink/clients/assetmanagement/models/_asset.py
> +    properties: Dict[str, str]
This also applies to `ConnectionHistory` below

2025-02-10 21:12 UTC, rbell517 commented on nisystemlink/clients/assetmanagement/models/_query_location.py
> +    response_format: ResponseFormat
response format and destination are both optional. Again, like export, I would not expect the user to set these and they would instead be set implicitly depending on the query function called

2025-02-10 21:12 UTC, rbell517 commented on nisystemlink/clients/assetmanagement/models/_query_location.py
> +    take: Optional[int] = None
Missing doc comment

2025-02-10 21:12 UTC, rbell517 commented on nisystemlink/clients/assetmanagement/models/_query_location.py
> +    end_time: Optional[str] = None
Missing doc comments for start and end time

2025-02-10 21:12 UTC, rbell517 commented on nisystemlink/clients/assetmanagement/models/_query_location.py
> +    continuation_token: Optional[str] = None
Instead of adding the continuation_token field you should change the base class to WithPaging to get this field. That will enable use to build some common paging functions.

2025-02-10 21:12 UTC, rbell517 commented on nisystemlink/clients/assetmanagement/models/_query_location.py
> +class ConnectionHistoryResponse(JsonModel):
This will match what we're doing in the other clients
```suggestion
class PagedConnectionHistory(WithPaging):
```
And remove the continuation_token field now that you're getting it from the base class

2025-02-10 21:12 UTC, rbell517 commented on tests/integration/artifact/test_artifact.py
Do not delete these tests. I'm guessing this was just a bad merge

2025-02-19 23:44 UTC, rbell517 commented on nisystemlink/clients/assetmanagement/models/_asset.py
> +    properties: Dict[str, str]
Cirpian just put up [an HLD](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullrequest/887785?_a=files&path=%2Fdocs%2Fdesign-documents%2FAsset%2FAsset-utilization-in-SLE.md) that indicates query-assets will be getting projection support, so we need to make sure all fields returned for queries are set to optional to avoid projection support integration being a breaking change for the client.

2025-03-11 08:52 UTC, CiprianAnton commented on nisystemlink/clients/assetmanagement/models/_query_assets.py
> +class QueryAssetRequest(JsonModel):
Please include totalCount as well. More details can be found in assetservice swagger

2025-12-22 09:58 UTC, closed without merging